import Header from "@/components/Header";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ background: "#27ecde" ,width : 'auto',margin : 0}}>
        <Header/>

        {children}
      </body>
    </html>
  );
}
